# Synchronous  Coros


TIP: All of the coros discussed in section of the document are lazy.

It is common for other languages or libraries to distinguish generators and tasks and to sub-categorize them into sync and promise.
This forces particular patterns on the user, which this library will try to avoid, hence the model is one unified type:

[source,cpp]
----
template<typename YieldSignature, typename ReturnType, typename Executor>
struct basic_coro;
----

The executor describes how to handle asynchronous events and is the basis for asio integration, which will be discusses later on.


[source,cpp]
----
template<typename YieldSignature, typename ReturnType>
using basic_coro = basic_coro<YieldSignature, ReturnType>;
----

The return-type is the final return of the basic_coro, while the yield-signature described how `co_yield` behaves.


Tasks
~~~~~


If the `YieldSignature` is `void` (or `void()`) the coroutine cannot use `co_yield` and is a task:


[source,cpp]
----
template<typename T>
using task = basic_coro<void, T>;


task<int> my_task()
{
    // do something
    
    co_return 42;
}


// use it
task<int> t = my_task();
assert(t.resume() == 42);
----

The `resume` function is used to advance the coroutine from one suspension point to the next. 

TIP: Lazy means they suspend directly after creation, i.e. the top of the basic_coro is a suspension point.

TIP: A Task can be task<void>.

NOTE: A `task` is directly `co_await`-able.

### Generators

The yield-signature can be used with an actual type to create a generator:


[source,cpp]
----
template<typename T>
using generator = basic_coro<T, void>;


generator<int> my_generator()
{
    for (int i = 0; i < 3; i++)
        co_yield i;
}

// use it
generator<int> g = my_generator();
assert(g.resume() == 0);
assert(g.resume() == 1);
assert(g.resume() == 2);
assert(g.resume() == std::nullopt);
----

Calling resume on a generator will return `optional<T>`, where T is the yield-result, so that a `nullopt` can indicate that the generator has `co_return`-ed.

Generating Tasks
~~~~~~~~~~~~~~~~

Combining tasks and generators is equally valid.

[source,cpp]
----
coror<int, std::string> my_task_gen()
{
    co_yield 42;
    co_return "done";
}

// use it
auto tg = my_task_gen();
assert(tg.resume() == 42);
assert(tg.resume() == "done");
----

The mixed type will return a `variant` even if the Return & Yield Types are the same, as to indicate when the coroutine returned.

Signatures & Pushing
~~~~~~~~~~~~~~~~~~~~

Up to now we have used a single concrete value for the YieldSignature, e.g. `int` which is equivalent to `int()`. 
Yield is a signature as to allow the user to push values into the basic_coro. This is expressed as `YieldResult(YieldInput)`.

[source,cpp]
----

basic_coro<double(int), void> bad_avg(double init = 0.)
{
    while (true)
    {
        int next = co_yield res;
        res = (next + res) / 2.;
    }
}

auto a = bad_avg();

assert(a.resume(0)   == 0.); // the input value gets ingored, because the basic_coro is lazy.
assert(a.resume(1)   == 0.);
assert(a.resume(3.5) == 0.5);
assert(a.resume(0.)  == 2.);
----

TIP: The result of the resume is from the previous calculation, because the basic_coro suspends with the last result and then resumes with new input value.

If the `YieldInput` is not void, resume takes a parameter that will get returned from the `co_yield` expression.

TIP: Coros of any kind can be safely destructed while they are suspended, which will unwind their frame.

NOTE: A push basic_coro, needs to be invoked before being `co_await`-ed, i.e. `co_await a(42);`

`noexcept`
~~~~~~~~~~

So far our coros have supported exceptions as a default, i.e.:

[source,cpp]
----
task<int> throwing()
{
    throw std::runtime_error(42);
    co_return 42;
}

auto t = throwing();
t.resume(); // throws runtime_error
----

It is however possible to declare a basic_coro `noexcept` which will cause the `resume` to be noexcept. Any exception leaving a basic_coro will cause termination. This can be done by declaring a yield-signature as noexcept:

[source,cpp]
----
basic_coro<void() noexcept, int> terminator()
{
    throw std::runtime_error(42); // will terminate the program
    co_return 42;
}

auto t = terminator();
static_assert(noexcept(t.resume())0;
t.resume();
----


Allocators
~~~~~~~~~~

It is be possible to pass custom allocators to coros. This will be done by passign `std::allocator_arg` and a following allocator into the basic_coro itself:

[source,cpp]
----
template<typename Allocator>
task<int> custom_alloced_task(int foo, int bar, std::allocator_arg_t, Allocator /*alloc */)
{
    
    co_return foo * bar;
}


custom_allocator alloc;
auto t = custom_alloced_task(21, 2, std::allocator_arg, alloc);
----


The coroutine promise will automatically pick this up.


Async
~~~~~

So far the corutines discussed are synchronous. That is, we call `resume` and 
expect the coroutine to complete on the same thread without any asynchronous delays. Consider the following code:

[source,cpp]
----
basic_coro<void> c()
{
    co_await awitable_signal(SIGINT);
}

int main()
{
    c().resume();
    return 0;
};
----

The main function resumes the coroutine, 
which then suspends to await a callback from somewhere else - what does main do now?

By default we would probably block, but this seems utterly inefficient. 
Thus a coroutine will have asynchronous resumptions that allow parallel usage of multiple 
coroutines.

[source,cpp]
----
basic_coro<void> c1()
{
    co_await awitable_signal(SIGINT);
}

basic_coro<void> c2()
{
    co_await awitable_signal(SIGTERM);
}

int main()
{
    array<basic_coro<void>, 2u> cs = {c1(), c2()};
    cs[0].async_resume([](auto){});
    cs[1].async_resume([](auto){});
    return 0;
}

----


An exemplary implementation can be found in [`asio::experimental`](https://think-async.com/Asio/asio-1.22.1/doc/asio/overview/composition/coro.html)