= Motivation

Many programming languages and runtimes
like node.js and python provide easy to use single-threaded concurrency frameworks.
While more complex than synchronous code,
single threaded asynchronicity avoids many of the pitfalls & overhead of multi-threading.

This library is meant to provide this to C++: *simple single threaded asynchronicity*
akin to node.js and asyncio in python that works with existing libraries like
`boost.beast`, `boost.mysql` or `boost.redis`.

It takes a collection of concepts from other languages and provides them based on  C++20 coroutines.

 - easy asynchronous base functions, such as an async main & threads
 - <<promise, promise>> & <<generator, generator>> types
 - <<op, operation wrappers>>
 - an <<with, async scope>>
 - <<select, select>>
 - <<channel, channel>>

Unlike `asio::awaitable` and `asio::experimental::coro`, `async` coroutines are open.
That is, an `asio::awaitable` can only await and be awaited by other `asio::awaitable`
and does not provide coroutine specific synchronization mechanisms.

`async` on the other hand provides a coroutine specific `channel`
and different wait types (`select`, `gather` etc.) that are optimized
to work with coroutines and awaitables.

