== delay
Let's start with the simplest example possible: a simple delay.

=== simple delay

.example/delay.cpp
[example]
[source,cpp]
----
include::../../example/delay.cpp[tag=timer_example]
----
<1> The <<main, co_main>> function defines an implicit `main` when defined
and is the easiest way to enter asynchronous code.
<2> Take the executor from the current coroutine promise.
<3> Use an argument to set the timeout
<4> Perform the wait by using asio::deferred.
<5> Return a value that gets returns from the implicit main.

In this example we use the <<main>> header, which provides us with a main coroutine if `co_main`
is defined as above. This has a few advantages:

 - The environment get set up correctly (`executor` & `memory`)
 - asio is signaled that the context is single threaded
 - an `asio::signal_set` with `SIGINT` & `SIGTERM` is automatically connected to cancellations (i.e. `Ctrl+C` causes cancellations)

This coroutine then has an executor in it's promisefootnote:[the promise the C++ name for a coroutine state.
Not to be confused with <<promise>>] which we can obtain through the dummy-<<awaitable, awaitable>>s in
the <<this_coro, this_coro>> namespace.

We can then construct a timer and initiate the `async_wait` with <<use_op>>.
`async` provides multiple ways to `co_await` to interact with asio, of which <<use_op>> is the easiest.

=== delay op

The problem with this interaction with asio is that asio doesn't do a pre-suspend check.
That is, the coroutine will suspend even if the timer is ready (because the delay is zero).

To leverage the coroutine properties, `async` provides an easy way to create a skipable operation:

.example/delay_op.cpp
[example]
[source,cpp]
----
include::../../example/delay_op.cpp[tag=timer_example]
----
<1> Declare the op. We inherit `op` to make it awaitable.
<2> The pre-suspend check is implemented here
<3> Do the wait if we need to
<4> Use the <<op, op>> just like any other awaitable.

This way we can minimize the amounts of coroutine suspensions.

