[#async_operation]
== Async operations

An async operation is an expression that can get called with a completion handler,
i.e. implements the `asio::async_operation` concept.

E.g. this is an `async_operation` with the completion signature  `void()`.

[source,cpp]
----
auto op = asio::post(ctx, asio::deferred);
----

Or the async_operation can be templated like this:

[source,cpp]
----
auto op = [&ctx](auto token) {return asio::post(ctx, std::move(token)); };
----

Note that `async_operations` will never complete immediately but always suspend the coroutine.

Depending on the completion signature the `co_await` statement may throw.

[cols="1,1,1"]
|===
| Signature | Return type | Exception

| `void()`                         | `void`             | `noexcept`
| `void(T)`                        | `T`                | `noexcept`
| `void(T...)`                     | `std::tuple<T...>` | `noexcept`
| `void(system::error_code, T)`    | `T`                | `system::system_error`
| `void(system::error_code, T...)` | `std::tuple<T...>` | `system::system_error`
| `void(std::exception_ptr, T)`    | `T`                | _any exception_
| `void(std::exception_ptr, T...)` | `std::tuple<T...>` | _any exception_
|===

[#enable_async_operation]
=== Enable async operation

Coroutines with this property will enable such coroutines to `co_await` asio-compatible coroutines.

Custom promised can add this functionality (through `await_transform`) by inheriting from `async::enable_async_operation`.
