[#channel]
== async/channel.hpp

Channels can be used to exchange data between different coroutines
on a single thread.

=== Outline

[source,cpp, subs=+quotes]
----
template<typename T>
struct channel
{
  // create a channel with a buffer limit, executor & resource.
  channel(std::size_t limit = 0u,
          asio::io_context::executor_type executor = this_thread::get_executor(),
          pmr::memory_resource * resource = this_thread::get_default_resource());
  // movable
  channel(channel && ) = default;

  /// Access the underlying executor
  using executor_type = asio::io_context::executor_type;
  executor_type get_executor() {return executor_;}

  // Closes the channel
  ~channel();
  // is the channel open?
  bool is_open() const {return !is_closed_;}
  // close the operation, will cancel all pending ops, too
  void close();

  // an awaitable that yields T
  using __read_op__ = __unspecified__;

  // an awaitable that yields void
  using __write_op__ = __unspecified__;

  // read a value to a channel
  __read_op__  read();

  // write a value to the channel
  __write_op__ write(const T  && value);
  __write_op__ write(const T  &  value);
  __write_op__ write(      T &&  value);
  __write_op__ write(      T  &  value);

  // write a value to the channel if T is void
  __write_op__ write();

};
----

=== Description

Channels are a tool for two coroutines to communicate and synchronize.

[source,cpp]
----
const std::size_t buffer_size = 2;
channel<int> ch{exec, buffer_size};

// in coroutine <1>
co_await ch.write(42);

// in coroutine <2>
auto val = co_await ch.read();
----
<1> Send a value to the channel - will block until it can be sent
<2> Read a value from the channel - will block until a value is awaitable.

Both operations maybe be blocking depending on the channel buffer size.

If the buffer size is zero, a `read` & `write` will need to occur at the same time,
i.e. act as a rendezvous.

If the buffer is not full, the write operation will not suspend the coroutine;
likewise if the buffer is not empty, the read operation will not suspend.

If two operations complete at once (as is always the case with an empty buffer),
the second operation gets posted to the executor for later completion.

NOTE: A channel type can be `void`, in which case `write` takes no parameter.

The channel operations can be cancelled without losing data.
This makes them usable with <<select, select>>.

[source,cpp]
----
generator<variant2::variant<int, double>> merge(
    channel<int> & c1,
    channel<double> & c2)
{
    while (c1 && c2)
       co_yield co_await select(c1, c2);
}
----


=== Example

[source,cpp]
----
async::promise<void> producer(channel<int> & chan)
{
  for (int i = 0; i < 4; i++)
    co_await chan.write(i);
  chan.close();
}

async::main co_main(int argc, char * argv[])
{
  async::channel<int> c{co_await async::this_coro::executor};

  while (c.is_open())
    std::cout << co_await c.read() << std::endl;

  co_return 0;
}
----

