[#config]
== async/config.hpp

The config adder allows to config some implementation details of boost.async.

=== executor_type

The executor type defaults to `boost::asio::any_io_executor`.

You can set it to `boost::asio::any_io_executor` by defining `BOOST_ASYNC_CUSTOM_EXECUTOR`
and adding a `boost::async::executor` type yourself.

Alternatively, `BOOST_ASYNC_USE_IO_CONTEXT` can be defined
to set the executor to `boost::asio::io_context::executor_type`.

=== pmr

Boost.async can be used with different pmr implementations, defaulting to `std::pmr`.

The following macros can be used to configure it:

 - `BOOST_ASYNC_USE_STD_PMR`
 - `BOOST_ASYNC_USE_BOOST_CONTAINER_PMR`
 - `BOOST_ASYNC_USE_CUSTOM_PMR`


If you define `BOOST_ASYNC_USE_CUSTOM_PMR` you will need to provide a `boost::async::pmr` namespace,
that is a drop-in replacement for `std::pmr`.

Alternatively, the `pmr` use can be disabled with

 - `BOOST_ASYNC_NO_PMR`.

In this case, async will use a non-pmr monotonic resource for the
synchronization functions (<<select,select>>, <<gather, gather>> and <<join, join>>)
and `use_op`. The `use_op` usage of this monotonic resource can be disabled by defining `BOOST_ASYNC_NO_MONOTONIC`.

