[#promise]
== async/promise.hpp

A promise is an eager coroutine that can `co_await` and `co_return` values. That is, it cannot be resumed.

[source,cpp]
----
async::promise<void> delay(std::chrono::milliseconds ms)
{
  asio::steady_timer tim{co_await async::this_coro::executor, ms};
  co_await tim.async_wait(async::use_op);
}

async::main co_main(int argc, char *argv[])
{
  co_await delay(std::chrono::milliseconds(50));
  co_return 0;
}
----

Promises can also be used to spawn tasks easily.

[source,cpp]
----
async::promise<void> my_task();

async::main co_main(int argc, char *argv[])
{
  +my_task(); // <1>
  co_await delay(std::chrono::milliseconds(50));
  co_return 0;
}
----
<1> By using `+` the task gets detached. Without the `+` it would generate a `nodiscard` warning.

=== Executor
[#promise-executor]

The executor is taken from the `thread_local` <<this_thread, get_executor>> function, unless a `asio::executor_arg` is used
in any position followed by the executor argument.

[source, cpp]
----
async::promise<int> my_gen(asio::executor_arg_t, asio::io_context::executor_type exec_to_use);
----

=== Memory Resource
[#promise-allocator]

The memory resource is taken from the `thread_local` <<this_thread, get_default_resource>> function,
unless a `std::allocator_arg` is used in any position followed by a `polymorphic_allocator` argument.

[source, cpp]
----
async::promise<int> my_gen(std::allocator_arg_t, container::pmr::polymorphic_allocator<void> alloc);
----

[#promise-outline]
=== Outline


[source,cpp]
----
template<typename Return>
struct [[nodiscard]] promise
{
  // movable
  promise(promise &&lhs) noexcept = default;
  promise& operator=(promise &&) noexcept = default;

  // enable `co_await`. <1>
  auto operator co_await ();

  // Ignore the return value, i.e. detach it. <2>
  void operator +() &&;
  // Cancel the promise.
  void cancel(asio::cancellation_type ct = asio::cancellation_type{0b111u});

  // Check if the result is ready
  bool ready() const;
  // Check if the promise can be awaited.
  explicit operator bool () const; // <3>
  // Get the return value if ready - otherwise throw
  Return get();

  // Detach or attach properties
  bool attached();
  void detach();
  void attach();

  ~promise();
};
----
<1> Supports <<interrupt_await>>
<2> This allows to spawn promised with a simple `+`, e.g. `+my_task()`.
<3> This allows code like `while (p) co_await p:`

[#promise-promise]
=== Promise

The thread promise has the following properties.

- <<promise_memory_resource_base>>
- <<promise_cancellation_base>>
- <<promise_throw_if_cancelled_base>>
- <<enable_awaitables>>
- <<enable_async_operation>>
- <<enable_await_allocator>>
- <<enable_await_executor>>

