[#select]
== async/select.hpp

The `select` function can be used to `co_await` one <<awaitable, awaitable>> out of a set of them.

It can be called as a variadic function with multiple <<awaitable, awaitable>> or as on a range of <<awaitable, awaitables>>.

[source,cpp]
----
async::promise<void> task1();
async::promise<void> task2();

async::promise<void> do_wait()
{
  co_await async::select(task1(), task2()); // <1>
  std::vector<async::promise<void>> aws {task1(), task2()};
  co_await async::select(aws); // <2>
}
----
<1> Wait for a variadic set of <<awaitable, awaitables>>
<2> wait for a vector of <<awaitable, awaitables>>

[#interrupt_await]
=== Interrupt Wait

When arguments are passed as rvalue reference, the select will attempt to use `.interrupt_await`
on the awaitable to detach the not completed <<awaitable, awaitables>>. If supported, the <<awaitable>> must complete immediately.
If the `select` doesn't detect the immediate completion, it will send a cancellation.

This means that you can reuse select like this:

[source,cpp]
----

async::promise<void> do_wait()
{
  auto t1 = task1();
  auto t2 = task2();
  co_await async::select(t1, t2); // <1>
  co_await async::select(t1, t2); // <2>
}
----
<1> Wait for the first task to complete
<2> Wait for the other task to complete

This is supported by <<promise, promise>>, <<generator, generator>> and <<gather, gather>>.

The `select` will invoke the functions of the `awaitable` as if used in a `co_await` expression
or not evaluate them at all.

[#left_select]
=== `left_select`

The `left_select` functions are like `select` but follow a strict left-to-right scan.
This can lead to starvation issues, which is why this is not the recommended default, but can
be useful for prioritization if proper care is taken.

