[#select]
== async/select.hpp

The `select` function can be used to `co_await` one <<awaitable, awaitable>> out of a set of them.

It can be called as a variadic function with multiple <<awaitable, awaitable>> or as on a range of <<awaitable, awaitables>>.

[source,cpp]
----
async::promise<void> task1();
async::promise<void> task2();

async::promise<void> do_wait()
{
  co_await async::select(task1(), task2()); // <1>
  std::vector<async::promise<void>> aws {task1(), task2()};
  co_await async::select(aws); // <2>
}
----
<1> Wait for a variadic set of <<awaitable, awaitables>>
<2> wait for a vector of <<awaitable, awaitables>>

The first parameter so `select` can be a https://en.cppreference.com/w/cpp/named_req/UniformRandomBitGenerator::[uniform random bit generator].


.Signatures of select
[source, cpp]
----
extern promise<void> pv1, pv2;
std::vector<promise<void>> pvv;

std::mt1337 rdm{1};
// if everything returns void select returns the index
std::size_t r1 = co_await select(pv1, pv2);
std::size_t r2 = co_await select(rdm, pv1, pv2);
std::size_t r3 = co_await select(pvv);
std::size_t r4 = co_await select(rdm, pvv);

// variant if not everything is void. void become monostate
extern promise<int> pi1, pi2;
variant2::variant<monostate, int, int> r5 = co_await select(pv1, pi1, pi2);
variant2::variant<monostate, int, int> r6 = co_await select(rdm, pv1, pi1, pi2);

// a range returns a pair of the index and the result if non-void
std::vector<promise<int>> piv;
std::pair<std::size_t, int> r7 = co_await select(piv);
std::pair<std::size_t, int> r8 = co_await select(rdm, piv);
----

[#interrupt_await]
=== Interrupt Wait

When arguments are passed as rvalue reference, the select will attempt to use `.interrupt_await`
on the awaitable to detach the not completed <<awaitable, awaitables>>. If supported, the <<awaitable>> must complete immediately.
If the `select` doesn't detect the immediate completion, it will send a cancellation.

This means that you can reuse select like this:

[source,cpp]
----

async::promise<void> do_wait()
{
  auto t1 = task1();
  auto t2 = task2();
  co_await async::select(t1, t2); // <1>
  co_await async::select(t1, t2); // <2>
}
----
<1> Wait for the first task to complete
<2> Wait for the other task to complete

This is supported by <<promise, promise>>, <<generator, generator>> and <<gather, gather>>.

The `select` will invoke the functions of the `awaitable` as if used in a `co_await` expression
or not evaluate them at all.

[#left_select]
=== `left_select`

The `left_select` functions are like `select` but follow a strict left-to-right scan.
This can lead to starvation issues, which is why this is not the recommended default, but can
be useful for prioritization if proper care is taken.


[#select-outline]
=== `Outline`

[source,cpp,subs=+quotes]
----
// Concept for the random number generator.
include::../../include/boost/async/select.hpp[tag=concept]

// Variadic select with a custom random number generator
template<asio::cancellation_type Ct = asio::cancellation_type::all,
         uniform_random_bit_generator URBG, awaitable ... Promise>
__awaitable__ select(URBG && g, Promise && ... p);

// Ranged select with a custom random number generator
template<asio::cancellation_type Ct = asio::cancellation_type::all,
         uniform_random_bit_generator URBG, range<awaitable> PromiseRange>
__awaitable__ select(URBG && g, PromiseRange && p);

// Variadic select with the default random number generator
template<asio::cancellation_type Ct = asio::cancellation_type::all, awaitable... Promise>
__awaitable__ select(Promise && ... p);

// Ranged select with the default random number generator
template<asio::cancellation_type Ct = asio::cancellation_type::all, range<awaitable>>
__awaitable__ select(PromiseRange && p);

// Variadic left select
template<asio::cancellation_type Ct = asio::cancellation_type::all, awaitable... Promise>
__awaitable__ left_select(Promise && ... p);

// Ranged left select
template<asio::cancellation_type Ct = asio::cancellation_type::all, range<awaitable>>
__awaitable__ left_select(PromiseRange && p);
----

