[#thread]
== async/thread.hpp

The thread type is another way to create an environment that is similar to `main`, but doesn't `signal_set`s.

[source,cpp]
----
async::thread my_thread()
{
  auto exec = co_await async::this_coro::executor;             // <1>
  asio::steady_timer tim{exec, std::chrono::milliseconds(50)}; // <2>
  co_await tim.async_wait(async::use_op);                      // <3>
  co_return 0;
}
----
<1> get the executor `thread` running on
<2> Use it with an asio object
<3> `co_await` an async operation

To use a thread you can use it like a `std::thread`:

[source,cpp]
----
int main(int argc, char * argv[])
{
  auto thr = my_thread();
  thr.join();
  return 0;
}
----

A thread is also an `awaitable` (including cancellation).

[source,cpp]
----
async::main co_main(int argc, char * argv[])
{
  auto thr = my_thread();
  co_await thr;
  co_return 0;
}
----

NOTE: Destructing a detached thread will cause a hard stop (`io_context::stop`) and join the thread.

WARNING: Nothing in this library, except for awaiting a <<thread>> and <<spawn>>, is thread-safe.
If you need to transfer data across threads, you'll need a thread-safe class,
e.g. https://www.boost.org/doc/libs/master/doc/html/boost_asio/reference/experimental__basic_concurrent_channel.html[`asio::conrurrenct_channel`].

=== Executor
[#thread-executor]

It will also create an `asio::io_context` to run on, which you can get through the `this_coro::executor`.
It will be assigned to the `async::this_thread::get_executor()` .

=== Memory Resource
[#thread-allocator]

It also creates a memory resource that will be used as a default for internal memory allocations.
It will be assigned to the `thread_local` to the  `async::this_thread::get_default_resoruce()`.

[#thread-outline]
=== Outline


[source,cpp]
----

struct thread
{
  // Send a cancellation signal
  void cancel(asio::cancellation_type type = asio::cancellation_type::all);

  // Add the functions similar to `std::thread`
  void join();
  bool joinable() const;
  void detach();

  // Allow the thread to be awaited
  auto operator co_await() &-> detail::thread_awaitable;   // <1>
  auto operator co_await() && -> detail::thread_awaitable; // <2>

  /// Move constructible
  thread(thread &&) noexcept = default;
  // Stops the io_context & joins the executor
    ~thread();
};
----
<1> Supports <<interrupt_await>>
<2> Always forward cancel

[#thread-promise]
=== Promise

The thread promise has the following properties.

- <<promise_cancellation_base>>
- <<promise_throw_if_cancelled_base>>
- <<enable_awaitables>>
- <<enable_await_allocator>>
- <<enable_await_executor>>

